### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by azadis** [GuyTevet/MotionCLIP#1]
Hi, Thanks for the great work. Do you have an estimate of when the code will be released?

**Comment by GuyTevet** [comment]
Thank you @azadis ! The code is expected in one or two weeks.

**Comment by zhiyuanGin** [comment]
one week has passed...

**Comment by zhiyuanGin** [comment]
hey man! two weeks nearly. Hah

**Comment by ZxyLinkstart** [comment]
Thank you for your contribution. I'm very interested in your work! I also want to know when the code will be released

**Comment by hanbyel0105** [comment]
I also want to know when the code will be released! Thanks for the great work!

**Comment by pszemraj** [comment]
Switzerland here, also looking for the code part of "paper with code."

**Comment by LinghaoChan** [comment]
> Thank you @azadis ! The code is expected in one or two weeks.

One moth has passed~~~

**Comment by GuyTevet** [comment]
Code is out:)

**Comment by Adrian-Serna** [comment]
Yes! thanks, she was waiting for this.
