### ISSUE TITLE
the test of editting and interpolation error

### ISSUE THREAD

**Issue by wang-zm18** [GuyTevet/MotionCLIP#10]
question like this:
![image](https://user-images.githubusercontent.com/47704679/187472548-4675c4bb-5475-479b-b5cb-081026ab2a30.png)

![image](https://user-images.githubusercontent.com/47704679/187473132-43e88856-865e-4469-86bd-5807f7b0c6d2.png)

**Comment by wang-zm18** [comment]
Is there something wrong with the parsing data processing?

**Comment by GuyTevet** [comment]
It looks like some of the data was not parsed into the `.pt` files (using amass_parser.py), maybe some of the datasets were omited?
Anyway, you can walk around this by deleting the text prompt that fails you from https://github.com/GuyTevet/MotionCLIP/blob/4cc3e6dca1ac03057b8916977cc1e61de70554d7/assets/paper_edits.csv
https://github.com/GuyTevet/MotionCLIP/blob/4cc3e6dca1ac03057b8916977cc1e61de70554d7/assets/paper_interps.csv
or select other prompts from your cache file `./data/amass_db/amass_30fps_all_text_labels.txt` instead.

**Comment by wang-zm18** [comment]
Thank you, @GuyTevet

**Comment by wang-zm18** [comment]
By the way, could you please show me catalogue of each subdataset in AMASS？I have downloded all subdatasets, and I guess maybe something wrong wth the extract process.
![image](https://user-images.githubusercontent.com/47704679/187570012-25297b24-15e3-48c9-8dfc-737c5045e420.png)

**Comment by wang-zm18** [comment]
Or could you please share the processed .pt files? Thank you in advance!

**Comment by GuyTevet** [comment]
Sharing the final .pt file will be the easiest also for me, but as far as I understand it will violate the copyrights of AMASS. If I misinterpret their license, I would be more than happy to share it.

This is how raw AMASS looks on my end:
![Screen Shot 2022-08-31 at 11 51 57](https://user-images.githubusercontent.com/24757373/187639082-cf9f4ca3-22f9-48bd-af06-838075414df6.png)

**Comment by wang-zm18** [comment]
OK, thank you! I indeed registered and accepted all licenses of AMASS, and downloaded all subdatasets. I cannot figure out what's the problem. I think maybe it does not violate  the copyrights...

**Comment by GuyTevet** [comment]
If you want, you can contact the data publishers to verify it with them. If they do approve, I will upload the `.pt`s

**Comment by wang-zm18** [comment]
OK， thank you!

**Comment by chenmozxh** [comment]
> Is there something wrong with the parsing data processing?

I encounter with the same error, Did you fix it?
