### ISSUE TITLE
Can not find "data/amass/amass_30fps_legacy_db.pt"

### ISSUE THREAD

**Issue by Ask-Yang** [GuyTevet/MotionCLIP#14]
I do parse data, but I can not find this file when I am doing text-to-motion.

**Comment by Kebii** [comment]
Have you solved this problem? I meet the same error when doing text-to-motion.

**Comment by Ask-Yang** [comment]
I don't remember much. May be you should change the console parameter.



---Original---
From: "Jiaxu ***@***.***&gt;
Date: Fri, Sep 22, 2023 11:06 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [GuyTevet/MotionCLIP] Can not find"data/amass/amass_30fps_legacy_db.pt" (Issue #14)




 
Have you solved this problem? I meet the same error when doing text-to-motion.

**Comment by dsdf783** [comment]
Could you kind share the file 'amass_30fps_legacy_db.pt' to me ? I can not correctly get it.
