### ISSUE TITLE
What is the script duration_finetunning.py used for?

### ISSUE THREAD

**Issue by nomorecoding** [GuyTevet/MotionCLIP#16]
Thanks for your great job!
I'm curious about the usage of duration_finetunning.py, is MotionCLIP trained in a two-stage manner? Namely, training Transformer AutoEncoder in the first stage, and finetune CLIP text-image encoder for the second stage. Am I understanding right?

**Comment by GuyTevet** [comment]
Hi! We do not fine-tune CLIP encoders (so it is just the first stage you described). I'm pretty sure that `duration_finetunning ` is not in use.
