### ISSUE TITLE
The generated action is reversed

### ISSUE THREAD

**Issue by sygyq305305** [GuyTevet/MotionCLIP#23]
I generated a Text-to-Motion based on readme and the following situation occurred.
![clip_text_paper_texts_fig_100](https://github.com/GuyTevet/MotionCLIP/assets/64886353/786a440d-641f-4012-a8df-d9a82a525d9e)
I want to know what caused it.

**Comment by GuyTevet** [comment]
Can you try and uncomment those lines:
https://github.com/GuyTevet/MotionCLIP/blob/0b32d39ef3b237c0f0dd02cd779c83829dc80527/src/visualize/anim.py#L104C1-L107C40

**Comment by sygyq305305** [comment]
Thanks for your help

**Comment by GuyTevet** [comment]
You're welcome:)
