### ISSUE TITLE
About AMSS Dataset

### ISSUE THREAD

**Issue by LinghaoChan** [GuyTevet/MotionCLIP#3]
In your [code](https://github.com/GuyTevet/MotionCLIP/blob/c2b9f40b0e721e42981f3e8b58133a1c51fde715/src/datasets/amass_parser.py#L69), one of the 'amass_train_split' list is 'BioMotionLab_NTroje'. I did not see it on the AMSS dataset. It is different from the code in [mass](https://github.com/nghorbani/amass/blob/08ca36ce9b37969f72d7251eb61564a7fd421e15/src/amass/data/prepare_data.py#L235).

**Comment by GuyTevet** [comment]
We will deliver a fix, but for now, you can switch `BioMotionLab_NTroje` with `BML` as in the source you pointed out.

**Comment by GuyTevet** [comment]
UPDATE: according to https://github.com/mkocabas/VIBE/issues/78,  `BioMotionLab_NTroje` is inside `BMLrub`.
