### ISSUE TITLE
'amass_30fps_legacy_db.pt' 

### ISSUE THREAD

**Issue by dsdf783** [GuyTevet/MotionCLIP#34]
Could you kind share the file 'amass_30fps_legacy_db.pt' to me ? I can not correctly get it.

**Comment by GuyTevet** [comment]
I can't because of copyright issues. Please send me an email.

**Comment by dsdf783** [comment]
thank you very much! 
lee12345677889@gmail.com

**Comment by dsdf783** [comment]
thank you very much! you are my life saver!
