### ISSUE TITLE
amass_30fps_db.pt file

### ISSUE THREAD

**Issue by meongeun** [GuyTevet/MotionCLIP#40]
Where can i get amass_30fps_db.pt file? 
I got error running this command.
 python -m src.visualize.motion_editing ./exps/paper-model/checkpoint_0100.pth.tar --input_file assets/paper_edits.csv

Provided amass data files are like this. Isn't it?  
amass_30fps_test.pt
amass_30fps_train-001.pt
amass_30fps_vald.pt

**Comment by Umang-edu** [comment]
I am getting the same error. How did you solve this error?
