### ISSUE TITLE
Training translation??

### ISSUE THREAD

**Issue by XiSHEN0220** [GuyTevet/MotionCLIP#6]
Hi, thanks a lot for sharing the code!!

I would like to confirm the training in translation. 

In the [training command you provided](https://github.com/GuyTevet/MotionCLIP#train-your-own) (`paper-model`), the translation is active(e.g. `--translation`).  

While in the paper, Sec.3 Method, you precise that p_i \in 24 * 6, which indicates the training should not involve the translation.
Also in the demo, it seems that the generated motion has no translation. 

Could you please be precise on this detail?

**Comment by GuyTevet** [comment]
Hi @XiSHEN0220 !
In practice, we learn translation anyway, but ignore it on visualization. We plan to add translation in the future, but this is not our top priority for now. Please reopen if you have any followups:)

**Comment by XiSHEN0220** [comment]
Thanks a lot!
