### ISSUE TITLE
How to get the rendered image and the rigged character?

### ISSUE THREAD

**Issue by yizhouzhao** [GuyTevet/MotionCLIP#7]
I appreciate this fascinating work so much. 

I have a question: how can we render the images and where is the file location for the rigged character?

![image](https://user-images.githubusercontent.com/21250552/176324836-89e9f9ab-489a-4f58-9c9b-8d46aa36501f.png)

Thank you so much!

**Comment by GuyTevet** [comment]
Hi @yizhouzhao !
We rendered AMASS frames using the [SMPL-X addon](https://www.youtube.com/watch?v=DY2k29Jef94&ab_channel=MichaelBlack) for Blender, with plain white background. The rigged character is just a SMPL-X female mesh ($\beta=0$) with the default texture provided by the addon.

**Comment by yizhouzhao** [comment]
Thank you so much!
