### ISSUE TITLE
Could we ignore global translation and only take joint rotation as input to MotionCLIP?

### ISSUE THREAD

**Issue by VigorZero** [GuyTevet/MotionCLIP#9]
Hi. I just wonder if we can ignore global translation and only take joint rotation as input to your pretrained MotionCLIP? Does this make sense? Thank you very much!

**Comment by GuyTevet** [comment]
Hi @VigorZero ! You can try switching this code:

https://github.com/GuyTevet/MotionCLIP/blob/4cc3e6dca1ac03057b8916977cc1e61de70554d7/src/models/modeltype/motionclip.py#L204-L206

with:

```
        # FIXME - TEMPORARILY SWAP AXIS FOR VISUALIZATION
        batch['output_xyz'] = torch.cat([batch['output_xyz'][:, :, 1:, :], batch['output_xyz'][:, :, :1, :]], dim=-2)
```

This will look bad for text2motion but should work well for editing applications.
